management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql-db
    username: root
    password: mysql
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true